# Generated by Django 5.0.7 on 2024-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('tier_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tier_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tier_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('method', models.CharField(max_length=50)),
            ],
        ),
    ]
