# Generated by Django 5.0.7 on 2024-08-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relics',
            old_name='type',
            new_name='mod_type',
        ),
    ]
