# Generated by Django 5.0.8 on 2024-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_type_relics_mod_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relics',
            name='method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
