# Generated by Django 5.0.8 on 2024-08-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_relics_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relics',
            name='tier_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='relics',
            name='tier_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
