# Generated by Django 5.0.8 on 2024-08-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_relics_tier_2_alter_relics_tier_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relics',
            name='tier_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='relics',
            name='tier_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relics',
            name='tier_3',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
