# Generated by Django 5.0.8 on 2024-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_relics_tier_1_alter_relics_tier_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relics',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relics',
            name='tier_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relics',
            name='tier_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
